### ISSUE TITLE
Unable to add an account with an identity_secret containing special characters

### ISSUE THREAD

**Issue by yellowbluebus** [soyware/MarketsBot#11]
When trying to add another account which contains "\\/" in the identity_secret string, the client complains with:

```
[04/15/2023 03:34:34 PM] Enter Steam Guard identity_secret (28 bytes): 3a\/XXXXXXXXXXXX=
[04/15/2023 03:35:24 PM] Enter Steam Guard identity_secret (28 bytes):
```
Tried escaping with '\' and single/double quote, no success.

**Comment by soyware** [comment]
is it 28 characters long? if it is, it must be because steam trades are down and we only continue if we get successful response

**Comment by yellowbluebus** [comment]
Yes, 28 chars long. I tried it with another account and it took it, so not sure if it's Steam or special characters. I can try again later with the account that's giving me issues, will update.

**Comment by soyware** [comment]
nvm, if confirmations request was failing you would be seeing "fetching confirmations" etc. "\\" isn't a valid base64 char, I assume it's used to escape "/" even though "\\/" isn't an escape sequence

**Comment by yellowbluebus** [comment]
Resolved! It did contain an extra escape character. I miscounted. My bad.
