### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Cosmic-Space** [soyware/MarketsBot#2]
Hello, after I copy the mapfile file to the folder in the software, I open the software and the mapfile file disappears. Can you prepare a video user guide about the software? thanks.

**Comment by soyware** [comment]
It's supposed to disappear as it gets imported into the config.

**Comment by Cosmic-Space** [comment]
Where am I doing wrong? Can you help me?
![1](https://user-images.githubusercontent.com/103674947/163456152-1e82bed7-de49-4cc3-a003-e93d3534567a.png)
![2](https://user-images.githubusercontent.com/103674947/163456940-4261e816-3386-4c2c-adb5-2b0b4c0dd759.png)

**Comment by soyware** [comment]
Do you use a proxy to connect to steam? Try opening [this link](https://api.steampowered.com/ITwoFactorService/QueryTime/v1?steamid=0) it should say "Method Not Allowed". I have just compiled and published the latest build, try using it, perhaps it fixes the issue

**Comment by Cosmic-Space** [comment]
I tried the last version and it works fine.thanks
