### ISSUE TITLE
Bot doesn't send offer for buyer.

### ISSUE THREAD

**Issue by Code404404** [soyware/MarketsBot#4]
Bot doesn't send offer for buyer. 

![Capture](https://user-images.githubusercontent.com/114101021/191572142-9748ce30-16f6-44b0-b56a-7f43126a3bc3.PNG)

**Comment by Code404404** [comment]
I found the solution, can you update your code for dota like code you write above which has 2 cases, for dota and csgo
![Capture](https://user-images.githubusercontent.com/114101021/191577190-905b8017-c819-4e93-af3d-ba875776cc2f.PNG)

**Comment by soyware** [comment]
Just tested buying an item works. You'll have to wait untill I get items and trade cooldown expires to test the selling

**Comment by Code404404** [comment]
Any updates?

**Comment by soyware** [comment]
Oh, you are right. Thanks. Pushed a hotfix, check release section.

P.S: I'm working on an update which will add proxy and multiaccount support and make the code less shittier.

**Comment by Code404404** [comment]
thanks
