### ISSUE TITLE
Error request failed: HTTP response code 500 

### ISSUE THREAD

**Issue by alifazani** [soyware/MarketsBot#6]
![image](https://user-images.githubusercontent.com/81021209/199972350-2f20f95a-4824-4736-b6fd-2bf4b03b5808.png)

I got this error.

**Comment by soyware** [comment]
Did you run Dota on that account? I heard Valve made it required for the account to have Dota been run for a few minutes, also make sure the account can trade

**Comment by alifazani** [comment]
Yes... Again, Valve blocks all trades for Dota 2

**Comment by soyware** [comment]
Try refreshing the inventory on the market, or maybe it's just Dota itself is lagging

Edit: looks like Steam is lagging - https://steamstat.us/

**Comment by alifazani** [comment]
Problem from steam server..I will close this issue
