### ISSUE TITLE
HTTP response code 429

### ISSUE THREAD

**Issue by bomber327** [soyware/MarketsBot#7]
Hello. I can't activate the program. When after entering the data writes this:
[24.12.2022 16:25:23] [Steam] Refreshing captcha...request failed (HTTP response code 429)

**Comment by soyware** [comment]
>The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").

try again later

**Comment by soyware** [comment]
assuming issue solved
