### ISSUE TITLE
Sometimes it stops working with queries

### ISSUE THREAD

**Issue by bomber327** [soyware/MarketsBot#8]
Thank you very much for the program!  This is what you need for manual trading. 

The only problem I noticed is sometimes it stops working with requests, it works after a reboot. 

And there is a question whether it is possible to somehow prescribe a password at startup so that every launch does not ask and it can be run on VDS.

**Comment by soyware** [comment]
I've published a version that seemingly fixes it, tell me if it keeps happening. I see no need for prescribing the password, just check your server periodically.

**Comment by bomber327** [comment]
https://prnt.sc/LnIcHWI2Cxze
The first requests do not pass through the api. I keep track of the rest. In any case, thank you for not abandoning the project!

**Comment by bomber327** [comment]
Requests are sent only by pressing Enter

**Comment by bomber327** [comment]
v0.3.1-hotfix2 fix this problem) thx) 
Are there plans to expand the functionality of the program and do you need help?

**Comment by soyware** [comment]
what do you want to be added?

**Comment by bomber327** [comment]
I use three scripts at the same time. Yours, the script for the auto-purchase of market csgo and for sale in buff.
I think the auto-purchase function would be appropriate here.
